# Generated by Django 3.2.3 on 2021-05-29 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='category',
            field=models.CharField(blank=True, choices=[('private', 'Приватно'), ('public', 'Публично')], default='public', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, choices=[('private', 'Приватно'), ('public', 'Публично')], default='public', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='album_author',
            field=models.ManyToManyField(default=1, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Автор Альбома'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ManyToManyField(default=1, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Фото'),
        ),
    ]
