# Generated by Django 3.2.3 on 2021-05-29 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0002_auto_20210529_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='favourites',
            field=models.ManyToManyField(db_table='alb_fav', related_name='fav_alb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='eyw_transactionref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='favourites',
            field=models.ManyToManyField(db_table='pic_favs', related_name='fav_pic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='user_pics', verbose_name='Фото'),
        ),
    ]
